language: java

cache:
  directories:
   - '$HOME/.m2/repository'

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token:
      secure: "$SONAR_TOKEN"
script:
   - mvn install
   - mvn clean package sonar:sonar
after_success:
   - mvn clean cobertura:cobertura coveralls:report