name: Infer Report

on:
  push:
    branches:
      - master

jobs:
  infer:
    name: Static analysis (Infer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Infer
        env:
          VERSION: "1.0.0"
        run: |
          wget "https://github.com/facebook/infer/releases/download/v${VERSION}/infer-linux64-v${VERSION}.tar.xz"
          tar xJf "infer-linux64-v${VERSION}.tar.xz"
          rm -rf "infer-linux64-v${VERSION}.tar.xz"
      - name: Run Infer
        env:
          VERSION: "1.0.0"
        run: |
          ./infer-linux64-v${VERSION}/bin/infer --version
          ./infer-linux64-v${VERSION}/bin/infer -- mvn -DskipTests=true clean package
      - name: Push to github infer-out branch
        run: |
          cd ./infer-out
          git config --global user.name "jiangxincode"
          git config --global user.email "jiangxinnju@163.com"
          git init
          git add .
          git commit -m "update infer-out"
          git push -f https://jiangxincode:${{secrets.GITHUB_TOKEN}}@github.com/jiangxincode/ApkToolBoxGUI.git master:infer-out